# Generated by Django 5.1.4 on 2025-05-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='Slider Görseli')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlık (Opsiyonel)')),
                ('caption', models.TextField(blank=True, verbose_name='Açıklama (Opsiyonel)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider Görseli',
                'verbose_name_plural': 'Slider Görselleri',
                'ordering': ['order'],
            },
        ),
    ]
